### ISSUE TITLE
Is Millstone GO enabled?

### ISSUE THREAD

**Issue by mlajoie** [churchlab/millstone#315]
It would be extremely useful to be able to classify mutations in genes of certain functions as defined by Gene Ontology. Is this functionality available?

**Comment by glebkuznetsov** [comment]
Won't implement for now.

**Comment by dbgoodman** [comment]
There are some non-trivial stats behind GO enrichment that would be both a
pain and an overreach to implement directly in Millstone, not to mention it
is unclear how one would link GO terms to the gene names (without
integrating it into the genbank file). I think the user is better off
extracting the gene names and then doing it him/herself.
