### ISSUE TITLE
Feature to allow importing samples from S3

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#375]
If the user has fastq data sitting in s3, we could imagine having a feature where they provide their s3 bucket credentials and Millstone imports from that location.  I haven't thought about the security implications of such a feature, so just a thought for now.

**Comment by glebkuznetsov** [comment]
Added to wish list.

**Comment by dbgoodman** [comment]
Definitely on my wishlist, esp. because it would mean that one wouldn't
have to have two copies of the data on the server (pre-load, and
post-load). The python S3 api is pretty good.
