### ISSUE TITLE
Batch upload through browser is wonky

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#470]
I uploaded 4 files total (rec01 and rec02 fastq files), and left for about 45 minutes:

![screen shot 2015-02-03 at 10 24 14 pm](https://cloud.githubusercontent.com/assets/515076/6035444/93e5e90e-ac01-11e4-8bff-fe99ae9c8bb6.png)

I came back, and the first 3 were done, but the last one was stuck on processing, despite the bar being at 100%. I closed the dialog (w/ Done) and the final file said 'Awaiting upload'. So I opened the dialog again and re-uploaded it. Here is what the dialog box looked like after it completed:

![screen shot 2015-02-04 at 12 04 53 am](https://cloud.githubusercontent.com/assets/515076/6035449/aa83f4a8-ac01-11e4-9302-b0cd9e843ded.png)

**Comment by glebkuznetsov** [comment]
Here's a specific example of a failure I just observed:

1. Upload template file (with filename errors).
2. Attempt to upload files.
3. Get message that the filenames don't match.
4. Fix and upload new template.
5. Use file upload again.
6. Observe that the previously attemped files are still int he processing queue.

I think we just need to make sure that the processing queue in the javascript upload widget is cleared after each failure.
