### ISSUE TITLE
Removing Picard's AddorReplaceReadGroups

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#478]
Adding read groups to the BAM files after alignment takes 5-10 minutes and Picard requires Java, which we might want to ditch at some point. 

Using the `-r` option to `bwa mem` allows us to add reads groups while aligning, removing this step.

http://seqanswers.com/forums/showthread.php?t=9180

E.g.:
```
bwa sampe -r "@RG\tID:ILLUMINA-52179E_0039_FC62HDBAAXX_1_1\tSM:48_2\tPL:illumina" ./testingscripts/chrY.fa ./testingscripts/48_2_1_KESC1_mymod.sai./testingscripts/48_2_2_KESC1_mymod.sai ./testingscripts/48_2_1_KESC1_mymod.fastq ./testingscripts/48_2_2_KESC1_mymod.fastq > ./testingscripts/chrYvs48_2_1_KESC1_mymod_48_2_2_KESC1_mymod.sam
```

**Comment by glebkuznetsov** [comment]
Fixed in 3451fd45b249e1123d57c5fcd4d943b47a7c0869
