### ISSUE TITLE
Allow velvet assembly on multiple samples

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#504]

**Comment by woodymit** [comment]
One way to do this would be to independently align multiple samples, extract SV-indicating reads, then concatenate all the different SV-indicating reads and feed them into velvet, but this does not leverage the fact that they come from different samples.  I'm going to check out http://m.bioinformatics.oxfordjournals.org/content/early/2015/04/28/bioinformatics.btv273.abstract and come up with a solution.

**Comment by dbgoodman** [comment]
Assembling reads across multiple samples blindly is *definitely* a no-go,
as it has the potential to generate non-existent chimeric contigs that
bridge multiple samples. One option would be to assemble contigs from each
sample separately, but then somehow merge or align the single-sample
contigs to see if multiple samples have the same or similar contigs. I'm
not sure yet how this merge/alignment step would work. Maybe if graph-based
assembly was a thing, it would be a snap.

---
Daniel B. Goodman
NSF GRFP Fellow
Division of Health Sciences and Technology
Massachusetts Institute of Technology
Bioinformatics and Integrative Genomics
P: (617) 459-2949 | E: dbg@mit.edu www.dbgoodman.com

**Comment by glebkuznetsov** [comment]
The merge step is the key contribution in the PopIns paper (
http://m.bioinformatics.oxfordjournals.org/content/early/2015/04/28/bioinformatics.btv273.abstract
).

**Comment by glebkuznetsov** [comment]
We are just independently parallelizing now.
