### ISSUE TITLE
Alternatives to celery

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#505]
Celery's canvas can't properly handle complex async job topologies.

This might be better: https://github.com/spotify/luigi

For more possibilities, see: https://github.com/pditommaso/awesome-pipeline/blob/master/README.md

**Comment by dbgoodman** [comment]
This sounds painful, but you are probably right that we should think about
switching at some point.

Also, I think it's funny/telling that celery is not on the list of
pipelines.



---
Daniel B. Goodman
NSF GRFP Fellow
Division of Health Sciences and Technology
Massachusetts Institute of Technology
Bioinformatics and Integrative Genomics
P: (617) 459-2949 | E: dbg@mit.edu www.dbgoodman.com

**Comment by glebkuznetsov** [comment]
Yeah I don't intend to do this right now. Just making a note for future us.

**Comment by glebkuznetsov** [comment]
Not happening.
