### ISSUE TITLE
VERIFYING should not block aligning.

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#532]
We don't need FASTQC to finish before running the alignment, and it can take a long time waiting. Rather than blocking the alignment until VERIFYING -> READY, we should allow alignment to begin while VERIFYING. Does anyone see any problems with doing this? If not I can implement.

**Comment by glebkuznetsov** [comment]
Sounds good to me.

**Comment by dbgoodman** [comment]
Still stuck on 'verifying' but in the code it looks like it should switch
to 'QC'. This might be an actual bug as opposed to a design flaw. I will
investigate.
