### ISSUE TITLE
Re-enable -a and -M in bwa mem if possible

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#536]
This requires fix the part of the de novo assembly code that deals with paired mates since the -a flag keeps secondary alignments around and hence introduces copies which assembly code currently doesn't expect.

**Comment by dbgoodman** [comment]
To be clear, we *do not* want to enable to -M flag (unless it is breaking
something separately that I'm not aware of). The -M flag is for picard
only, unless you are using the secondary alignments flag in your code.

**Comment by glebkuznetsov** [comment]
Ok good to know. Was confused because you left it commented out in the code.
