### ISSUE TITLE
millstone_setup.py doesn't work for some binaries, at least not for bwa

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#543]
I suspect f65d65e34f74c52e7a6cde445babef1a8364b855.

**Comment by dbgoodman** [comment]
Do you have any evidence to back up this wild accusation, sir?

**Comment by dbgoodman** [comment]
I just ran `python millstone_setup.py ` and got no errors. Can you post
yours?

**Comment by glebkuznetsov** [comment]
did it download bwa? :p
