### ISSUE TITLE
Need to update AMI id on RTD docs.

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#557]

**Comment by glebkuznetsov** [comment]
Here's the latest one:
ami-4b8d5220

We need to somehow remember to keep this updated when we release new AMIs. We probably need a new release "checklist". Here are some things that should be on it:

* Create a new machine from the new ami and run all tests on the new machine.
* Make new ami public and update docs with this ami
* Send a pull request to Brad Chapman to update cloudbiolinux (generally will only be a change to the hash of the latest stable Millstone instance)

**Comment by dbgoodman** [comment]
Release checklist is a great idea.
