### ISSUE TITLE
When sample_alignments > num_celery_workers, workers do not start the next job in the queue until all other workers also finish.

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#566]
I.e.: If you start an alignment with 5 samples and have 4 cores, the 5th sample isn't aligned until samples 1-4 finish, even if individual samples finish early. 

*This is anecdotal (on AWS w/ 4 cores), needs to be tested.*

**Comment by glebkuznetsov** [comment]
Don't think this is true. Re-open if observed again.
