### ISSUE TITLE
Periods in genome names causes Genome Feature tracks to fail. 

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#571]
In jbrowse, the Genome Features track, that should hold gene names, is blank.

For example, on AWS, for the genome U00096.2, there is an nginx error in `/var/log/nginx/error.log` that looks like: 

```
2015/08/03 20:42:39 [error] 1160#0: *977 open()
"/home/ubuntu/millstone/jbrowse/gd_data/projects/395a4175/ref_genomes/68cf8e35/jbrowse/indiv_tracks/gbk/tracks/gbk/U00096.2/trackData.json" failed (2: No such file or directory), 
client: 134.174.140.208, 
server: localhost, 
request: "GET /jbrowse/gd_data/projects/395a4175/ref_genomes/68cf8e35/jbrowse/indiv_tracks/gbk/tracks/gbk/U00096.2/trackData.json HTTP/1.1", 
host: "ec2-54-164-13-128.compute-1.amazonaws.com", 
referrer: "http://ec2-54-164-13-128.compute-1.amazonaws.com/jbrowse/index.html?loc=U00096.2%3A3740610..3740710&tracks=DNA&data=%2Fjbrowse%2Fgd_data%2Fprojects%2F395a4175%2Fref_genomes%2F68cf8e35%2Fjbrowse&highlight="
```

This file is indeed absent, but instead this file is present:

`/home/ubuntu/millstone/jbrowse/gd_data/projects/395a4175/ref_genomes/68cf8e35/jbrowse/indiv_t
racks/gbk/tracks/gbk/U00096/trackData.json`

You can see that it is looking for `U00096.2` but only `U00096` is present.

**Comment by glebkuznetsov** [comment]
This might be related to some combination of:

* The way we handle Chromosome names
* SeqRecord parsing

@woodymit might have a good idea about how to fix this.

**Comment by dbgoodman** [comment]
Pretty sure this is the issue:
https://github.com/churchlab/millstone/blob/master/genome_designer/main/model_view_utils.py#L82
