### ISSUE TITLE
AMI instances require valid github access/ssh keys to update millstone

### ISSUE THREAD

**Issue by mnapolitano89** [churchlab/millstone#592]

**Comment by dbgoodman** [comment]
This is a workaround:

1. Go to ~/millstone/.git/
2. Change this line:

`url = git@github.com:churchlab/millstone.git`

to 

`url = https://www.github.com/churchlab/millstone.git`

**Comment by glebkuznetsov** [comment]
This can be solved by using agent forwarding (include `-A` flag with `ssh`), or by doing what DBG says above. I don't think there's anything else we want to do.
