### ISSUE TITLE
There should be a wiki page on how to recover your password as an admin

### ISSUE THREAD

**Issue by mnapolitano89** [churchlab/millstone#599]
yeah....

**Comment by glebkuznetsov** [comment]
The only way to do it now is to change the password through the Django
shell.

Ideally would have email reset. Would have to do some more aws config for
that.

**Comment by mnapolitano89** [comment]
a guide on how to do that would suffice, I think

**Comment by glebkuznetsov** [comment]
Done:
https://github.com/churchlab/millstone/wiki/Recovering-forgotten-password
