### ISSUE TITLE
Add % read depth as a variant json column

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#602]
We need to be able to ask "What % of reads are alt" or "what % of reads support this event" at this locus. Currently we have depth by number, but by % is also informative. We might even want to have two values, one for % depth for all reads, and another for % depth of reads with good mapping quality.

**Comment by glebkuznetsov** [comment]
@dbgoodman Is this fixed in 
https://github.com/churchlab/millstone/commit/7a261e1f3367748cdee98fe3bf5864072bb9d43e and https://github.com/churchlab/millstone/commit/033af98f2e25ca5916602b9e9cf410778b9a2246?

**Comment by dbgoodman** [comment]
Should be. Let me pull your float fix and see if it works.

**Comment by dbgoodman** [comment]
Fixed by 7a261e1 and 033af98, and float bug that prevents filtering fixed by 3b3ae07.
