### ISSUE TITLE
Upload VCF Variant Set Fails

### ISSUE THREAD

**Issue by dbgoodman** [churchlab/millstone#604]
I took a SS of the error, but all the logs in /var/log/supervisor don’t show it.

Attached is the VCF file and screenshot of the error.
[tenaillon_ancestor.vcf.txt](https://github.com/churchlab/millstone/files/7188/tenaillon_ancestor.vcf.txt)
<img width="739" alt="screen shot 2015-10-03 at 12 06 16 pm" src="https://cloud.githubusercontent.com/assets/515076/10263770/a740c9e0-69c7-11e5-8fee-c80eda528aee.png">

I was trying to upload a 6.9kb deletion I found in the Tenaillon ancestor strain to make a reference genome that is closer to the samples (and also matches the loci positions used in the paper, which are relative to the ancestor).

**Comment by glebkuznetsov** [comment]
The error was caused because the input is bad. In the GT:DP entries for each sample you'll notice this entry which merges two entries: `./.:01/1:27`.
