### ISSUE TITLE
Probably should not store enormous refs or alts in the database

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#613]
I suspect this is slowing things down and potentially causing other bugs.

**Comment by dbgoodman** [comment]
what does 'enormous' mean?

**Comment by glebkuznetsov** [comment]
enormous equal to the size of the genome ~4.5 Mb

**Comment by glebkuznetsov** [comment]
I'm seeing this with, e.g. Pindel output

**Comment by dbgoodman** [comment]
ah, the ref/alt fields should be in SV format, so they don't need to hold
the ref/alt basepairs. My guess is the bug is how we convert to VCF from
pindel.

**Comment by glebkuznetsov** [comment]
we use an external script pindel2vcf

**Comment by glebkuznetsov** [comment]
Anyway, perhaps realted, I'm seeing a strange bug where annotations don't seem to be making it into the UI for all SVs from Pindel.

I'm looking at the 5 that were called by Pindel on Tenaillon Line12, and the 4 not annotated have the following in common versus the 1 that is correctdly annotated:

* no alt
* ref value on the order of the size of the genome
