### ISSUE TITLE
Can't start calling contigs for all samples if > 10 (view page size) contigs

### ISSUE THREAD

**Issue by glebkuznetsov** [churchlab/millstone#670]
No way to select all if multiple Datatables pages of contigs

**Comment by glebkuznetsov** [comment]
Now we're showing 100 samples so this is much less priority. Re-open if reported.

**Comment by dbgoodman** [comment]
Can we kick off two pages of samples simultaneously, or will kicking off a
second one break the first? If so, this is still an important bug to fix.

**Comment by glebkuznetsov** [comment]
Should be fine now but haven' tested. Re-open that more specific bug if it happens.
