### ISSUE TITLE
Is there any interactive/guided in-depth tutorial available?

### ISSUE THREAD

**Issue by WizardOfAus** [churchlab/millstone#703]
Hi,

Having no background in bio, is there any interactive/guided in-depth tutorial available?

**Comment by glebkuznetsov** [comment]
Hello,

There are is a link to a demo and some basic documentation available here:
http://churchlab.github.io/millstone/

There is more in depth explanation of case studies where Millstone has been used in the publication:
[Goodman, Daniel B., Kuznetsov, G. et al. "Millstone: software for multiplex microbial genome analysis and engineering." Genome Biology 18.1 (2017): 101.](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1223-1)

-Gleb
